workflows: # يجب أن تبدأ هذه الكلمة من أقصى يسار السطر بدون أي مسافات بادئة
  build-apk:
    name: Build APK
    max_build_duration: 15 # دقيقة
    environment:
      # بما أن هذا ليس مشروع Flutter، لا تحتاج لـ flutter: stable هنا.
      # إذا كنت تبني تطبيق React Native، قد تحتاج لتحديد إصدار Node.js
      node: 16 # على سبيل المثال، أو الإصدار الذي تستخدمه لمشروعك
    scripts:
      - name: Get dependencies # جلب التبعيات
        script: |
          # إذا كنت تستخدم npm
          npm install
          # أو إذا كنت تستخدم yarn، قم بإلغاء التعليق عن السطر التالي والتعليق على npm install
          # yarn install
      - name: Build app (مثال لـ React Native) # بناء التطبيق
        script: |
          # مثال: بناء APK لتطبيق React Native باستخدام Metro
          # npx react-native build-android --mode=release
          # أو إذا كان مشروع Expo، استخدم الأمر المناسب مثل:
          # eas build --platform android --profile production
          # تأكد من استبدال هذا السطر بأمر البناء الفعلي لمشروعك React Native/Expo.
    artifacts:
      # ستحتاج إلى تحديد مسار ملف APK الصحيح لمشروعك
      # مثلاً لـ React Native:
      # - android/app/build/outputs/apk/release/app-release.apk
      # أو لـ Expo:
      # - dist/*.apk
